name: Build JSDoc Documentation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install
        
      
      - name: Generate JSDoc
        run: npx jsdoc -c jsdoc.json
      
      - name: Deploy Documentation
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: gh-pages
          build_dir: docs
